trigger: none

pr: none

schedules:
- cron: "* * * * *"
  displayName: 25th 5:30 AM (IST) Every Month
  branches:
    include:
    -  master

- task: Bash@3
  inputs:
  targetType: 'inline'
    script: |
# Write your commands here
    
    echo 'Hello world'

# stages:
#   -stage: installjava
#     jobs: 
#       - job: installer
#         steps: 
#         - task: Bash@3
#           inputs:
#             targetType: 'inline'
#             script: |              
#               java --version
#               mvn --version
#       - task: PowerShell@2
#         inputs:
#           filePath: '$(System.DefaultWorkingDirectory)'

      
        # - task: Bash@3
        #   inputs:
        #     targetType: 'inline'
        #     script: |              
        #       mvn clean
        #       mvn install


  # - stage: install the script
  #   jobs:
  #     - job: installer
  #       steps:
  #       - task: ShellScript@2
  #         inputs:
  #           scriptPath: 'install.sh'       

  # - stage: Start the script
  #   jobs:
  #     - job: installer
  #       steps:
  #       - task: ShellScript@2
  #         inputs:
  #           scriptPath: 'start.sh' 

  # - stage: Deply to static web
  #   jobs:
  #    - job: deploy
  #      steps:
  #      - task: AzureStaticWebApp@0
  #        inputs:
  #          app_location: 'fe-asda-mock-test/install'
  #          output_location: 'private'
  #          azure_static_web_apps_api_token: 'abcd'

