trigger: none

pr: none

stages:
  - stage: installjava
    jobs: 
      - job: installer
        steps: 
        - task: JavaToolInstaller@0
          inputs:
            versionSpec: '8'
            jdkArchitectureOption: 'x64'
            jdkSourceOption: 'PreInstalled'

  - stage: installMaven
    jobs: 
      - job: installer
        steps:
        - task: Maven@3
          inputs:
            mavenPomFile: 'pom.xml'
            mavenOptions: '-Xmx3072m'
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.8'
            jdkArchitectureOption: 'x64'
            goals: 'clean install'
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean install'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false
 
  # - stage: install the script
  #   jobs:
  #     - job: installer
  #       steps:
  #       - task: ShellScript@2
  #         inputs:
  #           scriptPath: 'install.sh'       

  # - stage: Start the script
  #   jobs:
  #     - job: installer
  #       steps:
  #       - task: ShellScript@2
  #         inputs:
  #           scriptPath: 'start.sh' 

  # - stage: Deply to static web
  #   jobs:
  #    - job: deploy
  #      steps:
  #      - task: AzureStaticWebApp@0
  #        inputs:
  #          app_location: 'fe-asda-mock-test/install'
  #          output_location: 'private'
  #          azure_static_web_apps_api_token: 'abcd'