trigger: none
pr: none

stages:
  - stage: First
    jobs:  
      - job: stageone
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 1'
  - stage: second
    jobs:  
      - job: stagetwo
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 2'
 
