trigger: none
pr: none

stages:
  - stage: First
    jobs:  
      - job: stageone
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 1'
  - stage: second
    jobs:  
      - job: stagetwo
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 2'
 
  - stage: third
    dependsOn: second
    jobs:  
      - job: stagethree
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 3'
              
  - stage: Forth
    dependsOn: second
    jobs:  
      - job: stageforth
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 4'            
    
  - stage: Fifth
    dependsOn: second
    jobs:  
      - job: stagefifth
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 5'  

  - stage: Sixth
    dependsOn:
      - third
      - forth
      - fifth
    jobs:  
      - job: stagesixth
        steps:
        - task: Bash@3
          inputs:
            targetType: 'inline'
            script: |
              echo 'stage 6' 
 
